# Generated by Django 3.2.9 on 2021-11-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palaute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=50)),
                ('palaute', models.TextField(max_length=1000)),
                ('sposti', models.EmailField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Palvelu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palvelu', models.CharField(max_length=200)),
                ('hinta', models.CharField(max_length=200)),
            ],
        ),
    ]
