# Generated by Django 3.2.9 on 2021-11-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palaute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etunimi', models.CharField(max_length=50)),
                ('sukunimi', models.CharField(max_length=50)),
                ('palaute', models.TextField(max_length=1000)),
            ],
        ),
    ]
