# Generated by Django 3.2.9 on 2021-11-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ajanvaraus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=50)),
                ('sposti', models.EmailField(max_length=150)),
                ('puh', models.CharField(max_length=12)),
                ('osoite', models.CharField(max_length=150)),
                ('rekisterinumero', models.CharField(max_length=10)),
                ('vuosimalli', models.IntegerField()),
                ('merkki', models.CharField(max_length=20)),
                ('malli', models.CharField(max_length=150)),
                ('kilometrit', models.IntegerField()),
                ('lisatiedot', models.TextField(max_length=1000)),
                ('pvm', models.DateField(max_length=10)),
                ('klo', models.TimeField(max_length=10)),
            ],
        ),
    ]
