# Generated by Django 3.2.9 on 2021-11-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palaute',
            old_name='etunimi',
            new_name='nimi',
        ),
        migrations.RemoveField(
            model_name='palaute',
            name='sukunimi',
        ),
    ]
