# Generated by Django 3.2.9 on 2021-12-05 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_ajanvaraus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajanvaraus',
            name='valinta_palvelut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.palvelu'),
        ),
    ]
