# Generated by Django 3.2.8 on 2021-11-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211104_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palvelu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palvelu', models.CharField(max_length=200)),
                ('hinta', models.CharField(max_length=200)),
            ],
        ),
    ]
