# Generated by Django 3.2.8 on 2021-11-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palvelu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palvelu', models.CharField(max_length=200)),
                ('hinta', models.CharField(max_length=200)),
            ],
        ),
    ]
